/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.exebar.sandbox.java.core;

public class JApp {
    public String getGreeting() {
        return "Hello Java World!";
    }

    public static void main(String[] args) {
        System.out.println(new JApp().getGreeting());
    }
}
