/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.exebar.sandbox.kotlin.core

import org.junit.jupiter.api.DisplayName
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull

class KAppTest {
    @Test
    @DisplayName("App has a greeting")
    fun greeting() {
        val testGreeting = "Hello Kotlin World";
        val kApp = KApp(testGreeting)
        assertEquals(testGreeting, kApp.greeting)
    }

    @Test
    @DisplayName("App doesn't have to have a greeting")
    fun no_greeting() {
        val kApp = KApp(null)
        assertNull(kApp.greeting)
    }
}
