/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.exebar.sandbox.java.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JAppTest {
    @Test void appHasAGreeting() {
        JApp classUnderTest = new JApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
