/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.exebar.sandbox.java.core;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JAppTest {
    @Test
    @DisplayName("App has a greeting")
    void greeting() {
        String testGreeting = "Hello Java World";
        JApp jApp = new JApp(testGreeting);
        assertEquals("Hello Java World", jApp.getGreeting());
    }

    @Test
    @DisplayName("App doesn't have to have a greeting")
    void no_greeting() {
        JApp jApp = new JApp(null);
        assertNull(jApp.getGreeting());
    }
}
