#!/bin/bash

run_python_script() {
  /usr/bin/python3 $1
}

if [ $# -lt 1 ]; then
  echo "Usage: $0 <parameter>"
  exit 1
fi

if [ ! -x "$1" ]; then
  echo "$1 is not an executable file"
  exit 1
fi  

count=1
echo "Test Run #$count"

run_python_script "$1"

while true; do
  read user_input
  if [ -z "$input" ]; then
    clear
    let "count=count+1"
    echo "Test Run #$count"
    run_python_script "$1"
  fi  
done
