#!/bin/bash

file_last_access_timestamp() {
  local command_output=`stat -c "%Y" "$1"`
  echo "$command_output"
}

run_python_script() {
  `/usr/bin/python3 $1`
}

if [ $# -lt 1 ]; then
  echo "Usage: $0 <parameter>"
  exit 1
fi

if [ ! -x "$1" ]; then
  echo "$1 is not an executable file"
  exit 1
fi  

date +%H:%M:%S
$(run_python_script "$1")
last_access_timestamp=$(file_last_access_timestamp "$1")

while true; do
  current_access_timestamp=$(file_last_access_timestamp "$1")
  sleep 3
  if [ "$current_access_timestamp" -gt "$last_access_timestamp" ]; then
    date +%H:%M:%S
    $(run_python_script "$1")
    last_access_timestamp=$(file_last_access_timestamp "$1")
  fi
done
