/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.exebar.sandbox.kotlin.core

class KApp {
    val greeting: String
        get() {
            return "Hello Kotlin World!"
        }
}

fun main() {
    println(KApp().greeting)
}
